### ISSUE TITLE
add folder filesystem shortcut without scanning library

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#220]
Hello there, could you make the possibility to add a folder filesystem shortcut without scanning library
 At the moment if you do it it automatically adds it to the library, and scan takes ages. I just want a quick short cut to a folder. But with no scanning, like as if you went to it the long way round. 
Thanks for listening

**Comment by droidmjt** [comment]
shouldn't be too difficult, i'll see if I can get that added now

**Comment by droidmjt** [comment]
try the latest version, it works there.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/p4633mhy6uml428/droidsounde16647_09.apk?dl=0

**Comment by filevans** [comment]
I think that's the version I already downloaded about 4 or 5 days ago, 09,  
What is the difference between filebrowser and filesystem browser. Also there is folder, too

**Comment by droidmjt** [comment]
filebrowser is for SQL indexed stuff, filesystem browser is for files in the filesystem and not related anyhow to SQL

**Comment by filevans** [comment]
And 'folder'?

**Comment by droidmjt** [comment]
enter to filesystem browser and then in the above tab choose New -> Folder, it will create a folder without long scanning

**Comment by filevans** [comment]
Pressing + then folder for me just asks me to create a new folder I can't get it to point to a folder as a short cut. Also adding filesystem browser on this version is still scanning. If I make any changes to the folder I have to rescan the folder. I can't seem to just add a shortcut to my music folder without having to scan to update it

**Comment by droidmjt** [comment]
ah, my bad,i misunderstood this request. If i add the usual filebrowser without rescan, it won't show you anything since the stuff where you point it to, must be indexed to SQL database. This can only work with filesystem browser

**Comment by droidmjt** [comment]
more clarification:
filesystem browser -> raw file browser
filebrowser -> sql database browser

**Comment by filevans** [comment]
So can I add a shortcut to
 filesystem browser/sdcard/music/

And it simply show the files there as though you were going into filesystem browser the long way round, without having to scan. That's what in looking for, as it would be much easier that way. I make minor folder or file changes and I have to currently scan everything again

**Comment by droidmjt** [comment]
I'll change the filesystembrowser a bit

**Comment by filevans** [comment]
Great thanks

**Comment by droidmjt** [comment]
this is done

**Comment by filevans** [comment]
when i press on 'filesystem' now, nothing is showing up at all, completely blank with no directory structure, cannot see anything to press on

**Comment by filevans** [comment]
also tried to add a file browser short cut and nothing happens

**Comment by filevans** [comment]
adding a short cut to file browser still performs a full scan of the folder, not fixed

**Comment by droidmjt** [comment]
remove the existing filesystem-browser and create a new one, i tried with 3 different folders and worked as expected

**Comment by filevans** [comment]
Yes I've tried all that and as soon as I added it it dies a full scan, which I'm trying to avoid

**Comment by droidmjt** [comment]
i cannot reproduce your fullscan scenario, and you are 100% sure you try with filesystem-browser and not filebrowser? filesystem-browser is not even triggering fullscan in the code...weird

**Comment by filevans** [comment]
OK I completely deleted everything, forced closed program, restarted then added filesystem browser and it adds without scan. Great!! I don't know what was happening before but was scanning.
Just one minor problem now, is I want the link to be called 'Music' which is my folder name, but it adds generic 'filesystem', because I would also like to add one link 'sdcard' in case I want to browse other locatioms, but there is no folder name input, please could you just make it so it automatically calls the folder the parent folder you've added, no need to add a folder name input field. Just instead of filesytem, default name is exact name of parent folder added.

**Comment by droidmjt** [comment]
all right

**Comment by droidmjt** [comment]
so you want to have also multiple filesystem-browsers, lets see if its possible at all

**Comment by filevans** [comment]
well at least 2, one normal one for sd-card to explorer everything, and one to shortcut to my music folder, would be nice

**Comment by filevans** [comment]
Now I know why it was scanning when I tried to add the filesystem shortcut before, because you hadn't mentioned I had to delete the original filesystem, as it only allows one, if you try to add a new shortcut it scans..

**Comment by droidmjt** [comment]
great, anyway, this is done, now you can have unlimited amount of filesystembrowsers

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/uwebty4p3mp1wc6/droidsounde16647_11.apk?dl=0

**Comment by droidmjt** [comment]
test the above version please

**Comment by filevans** [comment]
OK this is working nice now

just the default filesystem link is redundant now as doesn't show anything when you click it, this link could be removed as default as the user can add their chosen location anyway

**Comment by droidmjt** [comment]
it is fixed now, it will add a working filesystem browser when you run it for the first time

**Comment by filevans** [comment]
this is happening again, i removed my computer music folder filesystem browser shortcut (because of not displaying sc68 files) readded it and upon readding it scanned the database, so this is not fixed, it wont avoid scanning database, when adding a filesystem browser is nothing to do with database

**Comment by filevans** [comment]
could this issue be reopened please

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2r2ocss1f4w71n1/droidsounde16647_24.apk?dl=0
i have all the sc68 files now in /sdcard/Music/sc.... folder, when i add new Filesystem browser, no rescan, nothing happens except the filesystem browser appears in the main menu, if it would rescan, i would see it since there are over 2000+ files to be scanned, i hope it works for you too

**Comment by filevans** [comment]
Yes that was working OK for me too, bit in this case I deleted a long standing folder and readded it and it rescanned

**Comment by droidmjt** [comment]
i'll try to hack something ....

**Comment by filevans** [comment]
yes just installed version _24 and still is scanning when you delete then re-add a filesystem browser short cut...

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/kkzac6e9cof45nm/droidsounde16647_25.apk?dl=0
try this

**Comment by filevans** [comment]
seems to be working ok now, just comes up for a second scanning, for some reason, just a second, then goes off, not sure why it even says it for a second, but anyway a lot better now seems to be, thanks a lot

**Comment by droidmjt** [comment]
in the main menu, all the items you see, Examples, DSEMusic etc etc, the usual items are from DB, it must be refreshes when a new item gets added to dsroot, thats why. close this case please.
