### ISSUE TITLE
option in settings to choose which folders are scanned in database mediastore

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#221]
At the moment it just scans the whole phone so you get things like notification tones and ringtones mixed up with the songs. Please could you put put an option in settimgs to select what folders you want scanned for the mediastor. Then it would be much better. Thank you for listening

**Comment by droidmjt** [comment]
its up to android system what it scans. Mediastore scan cannot be controlled.

**Comment by filevans** [comment]
On some music programs like poweramp you can choose which folders you want yo include to sans for media library
 But if not possible OK.

**Comment by filevans** [comment]
To scan

**Comment by droidmjt** [comment]
actually, i think i can get this fixed, the mediastore scanner will scan everything but I can change what it displays :)

**Comment by filevans** [comment]
Yes that is good. Could you let the user choose which folders are displayed then, in options. Check out how its done in poweramp, very good.
Thanks s lot

**Comment by droidmjt** [comment]
I will prevent the useless folders to be scanned and thats it.

**Comment by filevans** [comment]
What about an option to just display contents of 'music' folder. Then can just be a tick box

**Comment by filevans** [comment]
Sdcard/music

Option to just display that folder only please

**Comment by droidmjt** [comment]
all right,i'll see what i can do

**Comment by droidmjt** [comment]
I have implemented the folder selector now but just for interest, lets say you have 10 folders where MediaStore has scanned music, then you disable half of those, starting from Android 4.4 and after, you cannot tell MediaStore media scanner to refresh the folders, it has to be done one file at a time using a broadcast. 

I find this very cumbersome. How do you know PowerAmp is using MediaStore?

**Comment by droidmjt** [comment]
this is done

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/u1ythy8f5nnob7z/droidsounde16647_10.apk?dl=0

**Comment by filevans** [comment]
thanks testing everything now, useless folders in mediastore like 2x UI folders are still showing up, plus a raw folder

**Comment by filevans** [comment]
also could you default rescan database on start to "off" as when you install the program you to wait for a full scan and not able to disable it on first run

**Comment by droidmjt** [comment]
go to settings -> misc -> MediaStore folders and select your folders you want to use

**Comment by droidmjt** [comment]
i won't disable the rescan thing, this is because if the DB version/structure changes, full rescan is mandatory

**Comment by filevans** [comment]
I don't mean disable it, in options it is default ticked to scan in startup, if I am resting new versions I don't need to do full scan, you could just leave default to off just for start up only...

**Comment by filevans** [comment]
I selected just my music folder for media store and now I get lots of tracks that should all be one folder displaying as separate folders . should be grouped under one folder per album as it normally is

**Comment by droidmjt** [comment]
how is your music folder structure? is it something like sdcard/Music/Album1, sdcard/Music/Album2 etc etc

**Comment by droidmjt** [comment]
ok, this is what i did:
in /sdcard/Music folder, i created 3 new folders and under those 3 new folders I have X amount of Mp3 files, I had to wait until MediaStore scanner noticed them, after that, when i opened Local Mediastore, it showed me only those 3 new folders (albums) and inside the folders i saw mp3 files. Only thing i can do here anymore is add on-demand mediastore scanner.

**Comment by droidmjt** [comment]
finally, i was able to reproduce the problem, i'll fix it and add rescan option as well

**Comment by filevans** [comment]
If I select just my music folder, in mediastore, it displays say all 12 tracks of each album 12 times as a folder 
And when i click on any one if those 12 folders the album shows its files the same for each one

Then if I tick say music and another folder, nothing displays at all in media store, completely blank

**Comment by droidmjt** [comment]
yeah i got it, i have fixed this already, but there is one thing i cannot fix, those albums that are VA (Various Artists), the album name becomes always wrong, i verified this from mediastore sql db and its wrong there, but other than that, it should be ok now.

**Comment by filevans** [comment]
Brilliant

**Comment by filevans** [comment]
Yes one way around the VA - .... bull is put the mp3s through an ID3 tag editor, and either remove all tags or rename in bulk to something more cohearant, that's what I've been doing. 

Helps if sometimes you have an album where some of the MP3s tags are named differently so the android db displays the same album broken into multiple folders, I resolve this by either bulk removing tags for that album, or renaming all the files uniformly

**Comment by droidmjt** [comment]
hah, i cracked that damn VA problem, i hate this mediastore shit

**Comment by filevans** [comment]
Please could the scan on startup be disabled as default, or another option is a dialogue box upon running first time: database not found, proceed with scan? Yes/no.
Something like that, because when testing new versions you have to reset settings for it to work properly and is a bit annoying to be forced every time to wait for a full scan. Especially when you are not testing database related things

**Comment by droidmjt** [comment]
all right, i add that.

**Comment by filevans** [comment]
Also I've got a really good idea, when resetting settings after installing a new version, could it ask you: also delete database? Yes/no.

This way you choose not to lose your db. As when testing new versions you don't need to lose your db if you made no changes to your music folder...
And just wastes time deleting it then having to rescan

**Comment by droidmjt** [comment]
what database you are referring to?

**Comment by filevans** [comment]
The database where all your music collection is stored for browsing and searching in droidsound. This doesn't need to be deleted when resetting settings, unless you specifically request it

**Comment by droidmjt** [comment]
It should be already so that if you install a new version and your current DB version (database structure version) is up2date, it won't create a new songs.db, unless you check the checkbox from welcome message box (i will add that)

**Comment by filevans** [comment]
Yes but when you install a new version you get problems if you don't reset everything and restart. And when you do you lose your database, do would he better if asked you if you want to delete database too, when it says : are you sure you want to delete all settings, a tick box below (unticked by default) 'also delete database'

**Comment by droidmjt** [comment]
full rescan deletes database, nothing else

**Comment by droidmjt** [comment]
new install only deletes your preferences, maybe i can add a switch

**Comment by droidmjt** [comment]
but this is not related to mediastore anymore, close this case and open a new one with correct topic
