### ISSUE TITLE
Lots of songs show 'unknown - unknown'

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#228]
Lots of songs show 'unknown - unknown' (at least on amiga modules) So it impossible to know what song you are even playing. If there is no specific information available that the program needs, could the filename & extension be displayed here please, so we can just know what is currently playing. Thank you very much

**Comment by filevans** [comment]
(When song is playing in player)

**Comment by filevans** [comment]
Or just display like this instead of 'unknown':

filename.extension (for song title)
Parent folder (not full path) (for author)

**Comment by droidmjt** [comment]
send me few of these songs

**Comment by filevans** [comment]
I've just realised it happens just when you open the song from a file browser (es file explorer) not if you open it in the song browser in droid sound itself, 
Anyway all amiga .mod  files don't display artist, and has a blank space, please could you make it display parent folder for the song playing here, that would be very good

**Comment by droidmjt** [comment]
i'll add a generic location info in the player view, applies to every format

**Comment by filevans** [comment]
Yes as a lot if sc68 files show (unknown) where the author is, too

**Comment by droidmjt** [comment]
could you send me one of those files please

**Comment by filevans** [comment]
Sent 2. For you.

**Comment by droidmjt** [comment]
actually, that parent folder thing sounds a good idea, i'll use that.

**Comment by droidmjt** [comment]
this is done

**Comment by filevans** [comment]
sc68 files still saying unknown on some where artist is

**Comment by filevans** [comment]
basically exactly the same as it was before, saying unknown on lots

**Comment by droidmjt** [comment]
go to settings -> Misc -> use parent as dir

**Comment by filevans** [comment]
I've Ticked that and restarted and still get 'unknown' not working

**Comment by droidmjt** [comment]
damn it, i swear this worked, oh well, i'll check it

**Comment by droidmjt** [comment]
yeah it works when you search, not when you play, crap

**Comment by filevans** [comment]
This is good, but would be better if sid and any format that always shows author would be exempt from this override option. I could make a list of formats that should be exempt from override, or, even better would be an algorithm that only overides if 'nothing is displayed' or, artist says 'unknown'...

**Comment by droidmjt** [comment]
ok make a list

**Comment by filevans** [comment]
Yes

**Comment by filevans** [comment]
this still isnt working, when overriding unknown author with parent dir it is doing it for everything still, not just unknown or blank ones

specifically SC68 files are the best ones to test it with, as some have author and some say unknown, but with override on everything says the parent folder

if it isnt possible or too hard to do, would it be at least possible to make certain formats exempt from overide, like sid, and any other formats that always display author

**Comment by droidmjt** [comment]
send me one SC68 song where this happens

**Comment by filevans** [comment]
but folder name is overiding author always when ticked, for everything... not just sc68

**Comment by droidmjt** [comment]
in every view? I can't reproduce this

**Comment by droidmjt** [comment]
im trying to with Examples, happens only with few songs

**Comment by filevans** [comment]
it is overriding it with everything ive tested, ones that usually have an artist name

**Comment by droidmjt** [comment]
are you using archives or plain files?

**Comment by droidmjt** [comment]
ah now i was able to reproduce it, doesn't happen here always

**Comment by filevans** [comment]
just normal files, never use zip archives etc.

**Comment by filevans** [comment]
Is this fixed too in new version. Thanks

**Comment by droidmjt** [comment]
it should be, at least now i couldn't reproduce the problem anymore

**Comment by filevans** [comment]
Ok this is working great

But just needs one little tweak

On sc68 files next to authors name it would say the type of sc68 file it is, for example: 
Unknown (soundfx)

As there are different types of Amiga sc68 formats,(and as you know some don't play)

Well when you set to override with parent folder you lose the type of sc68 file it is too. Could this information in brackets be either kept, or better moved to the lines below where it says:
Plugin: sc68
Format: sc68 (here put sc68 type - soundfx etc)

**Comment by droidmjt** [comment]
i'll try to get it in Format:

**Comment by filevans** [comment]
Yes better in format rather than author . that's accurate

**Comment by droidmjt** [comment]
this is fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/5tjz4298o0fvquq/droidsounde16647_17.apk?dl=0

**Comment by droidmjt** [comment]
the above build fixes the problem

**Comment by droidmjt** [comment]
now when you install a new build, remember to untick the rescan box

**Comment by filevans** [comment]
i think that override unknown/ blank author with parent folder should be default as it is not interfering now with author information already there, and only filling a gap, no one would need to turn that off, doesnt really need to be selectable as an option

**Comment by filevans** [comment]
could you just set this option as as default then im happy, and close case

**Comment by filevans** [comment]
just one thing more thing here. in browser, all mod files (and some SNES and sc68 files) say 'unknown' as the artist, not in player anymore, just in browser list, would it possible to make all unknown list here as parent folder too?
would be much better

**Comment by droidmjt** [comment]
I won't put it as a default because i let users decide whether its default or not. "just one thing more..." you said it twice now, i'll close this case :)

**Comment by filevans** [comment]
but still in the browser list they are displaying unknown, could you put them to show the parent folder there then at least

**Comment by droidmjt** [comment]
done

**Comment by filevans** [comment]
thanks, could you upload fixed version thanks

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ei0an80adk5gqek/droidsounde16647_18.apk?dl=0

**Comment by filevans** [comment]
![screenshot_2015-12-26-20-04-47](https://cloud.githubusercontent.com/assets/14978933/12008371/07a8ac6c-ac0d-11e5-9a81-51a95424774f.png)
![screenshot_2015-12-26-20-04-56](https://cloud.githubusercontent.com/assets/14978933/12008372/07aa768c-ac0d-11e5-9fc1-6bb5c4318f60.png)

not fixed still look, working ok on mod, but on sc68 notice it shows unknown for author for the unknown ones, so the folder name is not overriding it, and for the known authors it is overriding it when shouldnt be...

**Comment by filevans** [comment]
look on player it is perfect, shows 1930 is by Keo, but in browser it overrides it to folder name when shouldnt

then on the unknown ones it is not overriding it

**Comment by filevans** [comment]
also there are quite a lot of sid tunes that have <?> for the author, could those be included into overide by parent folder, on player and browser

**Comment by droidmjt** [comment]
i check it

**Comment by droidmjt** [comment]
those others  i could fix where unknown had space format but the Keo thing, i cannot reproduce

**Comment by droidmjt** [comment]
i created identical folder what you have in Keo case and i cannot make it override, i'll upload new binary now, the SID thing is fixed there too.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/v9w6gvwt8qod2xr/droidsounde16647_19.apk?dl=0

**Comment by filevans** [comment]
Keo is the author, it should not override it

In browser was overriding with parent folder name.

OK I'll test again the new one

**Comment by filevans** [comment]
![screenshot_2015-12-27-09-35-32](https://cloud.githubusercontent.com/assets/14978933/12010476/154c54b4-ac7f-11e5-9945-86e2616cf285.png)
![screenshot_2015-12-27-09-35-27](https://cloud.githubusercontent.com/assets/14978933/12010477/154da378-ac7f-11e5-90e4-f01935dc54d1.png)

**Comment by filevans** [comment]
tested new version now

look in player 5th Gear is by Jochen Hippel, for example, but in browser all the artists are being overrided, should only override the unknown ones...

**Comment by filevans** [comment]
<?> on c64 is fixed, thanks a lot

**Comment by droidmjt** [comment]
i can't reproduce this, seriously, i really can't

**Comment by filevans** [comment]
it is genuinely happening, ill try to completely uninstall, reinstall, clear settings and restore gui, and see if that fixes it

**Comment by droidmjt** [comment]
stop posting these issues,

**Comment by filevans** [comment]
do you have collection of SC68 files to test properly?

**Comment by filevans** [comment]
Ive just uploaded complete SC68 (amiga) set for you 

http://www.mediafire.com/download/dkxr7ritlbk7ylx/SC68.rar

15mb archive

**Comment by filevans** [comment]
i did complete uninstall, reinstall, reset settings and then full rescan of database and fixed the problem, they are displaying correctly now in browser, sorry about that, thank you for fixing it

well done mate

**Comment by filevans** [comment]
just 2 quick questions
if i compress some of my folders, what format do you suggest I use: zip, rar, or rar solid archive? i tried rar solid archive as gives the best compression but was very slow scanning

also in browser, when you hold down on database folder, i chose rescan database there, is that full scan or just check for orphans scan?

**Comment by droidmjt** [comment]
pack using normal zip, no compression for already compressed songs, normal compression for compressed, never use solid option in any formats, extracting takes too much time and resources. when you hold down on archive and choose rescan, its full scan only for that archive, nothing else gets scanned, for your favourite formats its quite fast.

**Comment by filevans** [comment]
when you hold down on a database folder, it would be good if it was labelled "full scan" so you know what type of scan it is
and also an option to do light scan too there would be good, as i like to use it there as quicker than going into the settings menu

**Comment by filevans** [comment]
there is still one minor glitch with this

when you move to subsongs on '.cust' / 'cust.' amiga modules, the "folder as author" no longer displays and goes blank

it is ok for track number 1, but when you advance to track 2 subsong, it disappears, ive took 2 screenshots, notice after advancing to subsong 2:

![screenshot_2015-12-28-11-25-42](https://cloud.githubusercontent.com/assets/14978933/12052772/95a8f1c4-aee8-11e5-9aa4-e5059c139e39.png)
![screenshot_2015-12-28-11-25-46](https://cloud.githubusercontent.com/assets/14978933/12052777/9943bd50-aee8-11e5-9767-f9a0f68bb351.png)

**Comment by droidmjt** [comment]
ah, crap, i fix it

**Comment by sketch242** [comment]
Not really relevant to fixing the problem, but just wanted to point out that if your files are named "Author - Title.extension", droidsound will show the proper author and title for songs which don't contain author and title info.  I wrote a script to rename files from modland into a format more suitable for droidsound.  I can put it somewhere if it would be useful for anyone.

Also, I too found that most Amiga SC68 files won't play with droidsound, but the much larger collection on http://sc68.atari.org/musics_all.html will.

**Comment by droidmjt** [comment]
@sketch242 thanks for sharing the infos, personally i never listen sc68 files, its sndh + UADE files. SC68 amiga songs are just conversions of UADE songs, but thats just me.

**Comment by filevans** [comment]
the author problem im getting on .cust / cust. amiga modules rather than sc68

but that info is very good, i had a suspision of something like this, because i noticed there is eliminator title music as an sc68, but also exists as 'cust' module too, and plus on exotica who have a brilliant databast of amiga modules never use sc68, they have custom modules instead

plus related to this is the soundfx modules which seem to also exist in an sc68 container which dont play properly

**Comment by sketch242** [comment]
I always assumed the Amiga SC68 files were like Amiga PSID files, where the songs were converted to some standardized format that could be played by an emulator which ran as a delitracker plugin.  But it never gained much popularity, unlike SID emulators, so not much can actually play them and there aren't all that many songs.

**Comment by filevans** [comment]
there are quite a lot of amiga sc68 songs, this is my complete collection, 608 songs, all of them amiga, no ST. and a lot of them also  have subtunes

http://www.mediafire.com/download/dkxr7ritlbk7ylx/SC68.rar

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/8kq1rzhqe21aqje/droidsounde16647_20.apk?dl=0

**Comment by filevans** [comment]
this is working now, but could you untick the option to to have normal click to sort as default, as it is better as a long click, and if people want tap then they can tick it

**Comment by filevans** [comment]
@sketch242 
"Also, I too found that most Amiga SC68 files won't play with droidsound, but the much larger collection on http://sc68.atari.org/musics_all.html will."

this is not true, i downloaded this package, and all the same ones that wont play in the other sc68 wont play in this one either, it is basically the folder marked 'unknown (soundfx)' from this archive, none of them will play, exactly the same files from my archive, the only difference is they are all mixed in with the other ones in my archive so it appears as you are going through a lot wont play, whereas in this archive they are seperated out, so you dont come across them until the end of the archive - folder alphabetically beginning with U.....

**Comment by filevans** [comment]
im going to go through all the unknown (soundfx) files and see if they are available in another format on exotica etc. and download them all there, and see if they play, will let you know

**Comment by filevans** [comment]
yes basically that resolves it,  you can replace most of the files from the sc68 unknown soundfx folder by getting the original soundfx files from exotica, for example, 'Another World - Intro.sc68' (and outro) which is a soundfx format in sc68 container you can get on exoctica:

http://www.exotica.org.uk/wiki/Another_World

contains exactly the same music here, but in pure soundfx format, and plays fine on my pc using BZRPlayer (which wont play the SC68 file)  using FLOD engine (rather than UADE) 

ill test these files now on droidsound

**Comment by filevans** [comment]
yes these soundfx files play on droidsound, it uses UADE, so that resolves the problem if you try to replace all the sc68 soundfx with real soundfx files .sfx/sfx.

**Comment by filevans** [comment]
some songs i can't find (specifically demo songs) but most are there, all the games are there

**Comment by sketch242** [comment]
@filevans Actually, you are right about the SC68 archive, my memory is faulty. I only have a SNDH archive on my phone currently.  I think I gave up on playing SC68 files because so many didn't work, when I first installed the original droidsound (not DS-e).  Maybe I'll revisit SC68 after I finish working my way through the ASMA (.sap) archive.

**Comment by filevans** [comment]
its not that many that dont work actually, everything should play except the folder unknown (soundfx) 

that is 155 songs out of 610 songs dont play

**Comment by filevans** [comment]
I copied the sc68 files from the other new archive the files are categorized into author folders, but got a problem where in browser it is not showing the correct title of the file and instead showing a subsong title, in a lot of cases 'intro' could out fix this please

**Comment by droidmjt** [comment]
are you using archive or plain files? copied from which archive, the one that contains all the sc68 files?

**Comment by filevans** [comment]
![screenshot_2015-12-31-16-57-36](https://cloud.githubusercontent.com/assets/14978933/12071380/d9988708-b07f-11e5-99b9-e3f9504a51b7.png)

yes plain files, look

**Comment by droidmjt** [comment]
i'll check it

**Comment by filevans** [comment]
first 'intro' should be '7 gates of zambala', and second 'intro' should be 'chambers of shaolin' and 'Title' should be 'Leavin' Teramis (AGA)' etc....

**Comment by droidmjt** [comment]
no, the stuff comes from SC68 header, 7 Gates of Jambala.sc68 file's title is 'Title'. The parser is following the naming properly.

**Comment by filevans** [comment]
But that is no good in browser, browser should show title of game or module

**Comment by filevans** [comment]
Title is the name of the first subsomg that's why,
 Shouldnt display that is browser

**Comment by droidmjt** [comment]
ah, got an idea

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/teemqfclsp7wz3h/droidsounde16647_23.apk?dl=0

**Comment by filevans** [comment]
this is fixed now
but the only thing is, when you press on the song in player it now doesnt show the subsong name at all when advancing through them

it would be good it said it like this in player:
---------------------------------
5th Gear - subsong name
Jochen Hippel
---------------------------------

would that be possible

**Comment by droidmjt** [comment]
it is like that already, after the songname there is subtitle displayed in () if subsong name is different than the filename

**Comment by filevans** [comment]
No. Tested it, nothing displayed. Should say intro as we agreed for 7 gates if zambala for first subsong

**Comment by droidmjt** [comment]
![subtune](https://cloud.githubusercontent.com/assets/5917820/12077743/62b6b104-b1fc-11e5-998a-f68dda77be86.png)

**Comment by droidmjt** [comment]
see the title and close this case

**Comment by filevans** [comment]
yes im testing new version now

**Comment by filevans** [comment]
yes i apologise i was testing it in 5th gear the first song, which has 5 subsongs but as they dont have any information header then not displaying anything, so that is normal. i see now on 7 gates of jambala has subsong title in brackets, thank you very much for doing a good job on everything
