### ISSUE TITLE
Memory leak with archive extraction

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#272]
All of my songs are stored in 7z archives. When i start a bunch of them by repeatedly pressing "next", memory usage keeps increasing. The effect persists if I open a file in another folder, unloading the prior playlist. So there is no way to unload files, except restarting the program entirely.

Memory appears to be bounded if i just open the same files over and over again. (also no extraction? delay)

However, merely opening six PSF files brings memory usage to 200MB, a significant chunk of my device's memory. Shouldn't you be unloading old files,  after advancing songs (or maybe a few songs later), or when switching folders/playlists?

**Comment by droidmjt** [comment]
This seems to happen with 7z archives that use Solid-Block option, if you don't use solid option it works fine. Even tho solid option consumes memory, it should free it, i'll check it.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/a2ugdjc8u2fplb6/droidsounde16647_43.apk?dl=0

**Comment by jimbo1qaz** [comment]
Crashes on SPC play :(

**Comment by droidmjt** [comment]
you need to reset preferences from settings, I added a new option.

**Comment by jimbo1qaz** [comment]
Clear prefs and cache = crash on SPC 
Wipe app data = crash on launch app

**Comment by droidmjt** [comment]
send crashlogs / logcat logs.

**Comment by droidmjt** [comment]
nevermind i was able to reproduce the second crash

**Comment by droidmjt** [comment]
This is fixed, will upload new binary later today.

**Comment by jimbo1qaz** [comment]
Did you upload the apk?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/rq5nq0xbeax0lvc/droidsounde16647_44.apk?dl=0

**Comment by jimbo1qaz** [comment]
only works on cm12.1 lg g2.

still crashes on cm11 galaxy nexus.

**Comment by droidmjt** [comment]
i need crashlog, without crashlogs i cant fix anything

**Comment by droidmjt** [comment]
fixed, uploading new binary

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ehwhpjtfskr23z0/droidsounde16647_45.apk?dl=0

**Comment by jimbo1qaz** [comment]
What crash logs? Logcat?

**Comment by droidmjt** [comment]
nevermind its fixed in _45 binary, closed a file too early, thats why it crashed.

**Comment by jimbo1qaz** [comment]
Cm11: dsemusic is empty. Rescan, then dsroot is empty. Crashes when loading from file manager.

**Comment by droidmjt** [comment]
all right, close this case and open a new one with correct topic

**Comment by droidmjt** [comment]
That's just a minor bug in recognizing "new" version.
