### ISSUE TITLE
Droidsound-E doesn't support other languages

### ISSUE THREAD

**Issue by Andr20** [droidmjt/Droidsound#503]
Lately i discovered again the following problem, some songs are not showed correctly, for example it happens with Cyrillic alphabets and all the special letters used in Italian ò,à,è,ù or Swedish ö,ä,å, this it happens with all language using special letters, it would not be a problem if droidsound would not get stuck everytime when some song with those letters are being played, in the past was just jumping to the next song now it get stuck completely.

**Comment by droidmjt** [comment]
does the problem appear if I rename some random mp3 file using those letters?

**Comment by Andr20** [comment]
Using this option sometimes it works sometimes not, and streaming files via http or ftp it gives always this problem

**Comment by droidmjt** [comment]
I just renamed one song file to use those letters and no problems. You need to provide steps how to reproduce the problem or I will close this issue.

**Comment by Andr20** [comment]
it happens always when you stream files from ftp or http, i can send the link so you can see the issue

**Comment by droidmjt** [comment]
yes, please send some http links

**Comment by Andr20** [comment]
at the moment i have my own ftp link that i can send privately via mail, the http link i have to find again on internet so i need time

**Comment by droidmjt** [comment]
Please find the HTTP link if possible.

**Comment by Mart769** [comment]
I am really happy to use this program and I decided to sign in and explain my situation, I use it also with http, I had this problem in the past, then I discovered that is a problem with the kind of rules the server is giving for the stream, but it should work modifing some part of the address , unfortunately is a bit hard to find some http audio streaming from normal audio file still but are only radio streaming and radio streaming works well, instead I have the same problem streaming the FTP from WDmyCLOUD or also normal FTP server, living in Russian I have most of the songs written in Cyrillic so I have problems with it, I am really happy to use this player but the FTP make it really impossible to use, with the right rules is possible to stream HTTP without problems, but FTP not, some android players are able to use FTP correctly also with special letters, but the time it takes the song to be streamed is not fast at all like Droidsound-e, other player are downloading, then they play the song, droidsound it gives the option to donwload or stream directly

**Comment by droidmjt** [comment]
ok so if I setup an FTP server and copy there an mp3 using some cyrillic letters in the filename, it should fail?

**Comment by Andr20** [comment]
OK Mart769 thanks, when i have the opportunity i'try, i want try but at the moment i dont have the opportunity to try because is not simple to find and about the FTP, yes, it give this problem, with Cyrillic and othe special letters used in other languages

**Comment by droidmjt** [comment]
all right, I'll investigate it

**Comment by Mart769** [comment]
Yes right, in FTP you can see the issue already from the Explorer, hope I was explaining the solution with the HTTP well
Thanks droidmjt!

**Comment by Andr20** [comment]
![Screenshot_20190704-171342](https://user-images.githubusercontent.com/16883718/60676763-fc279b00-9e7f-11e9-9074-ac2b90ea88ca.png)
![Screenshot_20190704-171920](https://user-images.githubusercontent.com/16883718/60676765-fc279b00-9e7f-11e9-9127-d980bb5c03d5.png)

this is the issue

**Comment by droidmjt** [comment]
I fixed the language problem already, but there is another thing I need to fix

**Comment by Andr20** [comment]
WOW perfect. THANKS droidmjt!!!!!

**Comment by Mart769** [comment]
OMG thank you! Finally i can stream music from my own country!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/35r2nv1wszfk8jz/droidsounde167_173.apk?dl=1
try this, at least I was able to play and seen cyrillic letters in my FTP

**Comment by Andr20** [comment]
Thanks, with explorer it works, when is paying i know it give the problems still, this i understand but is already perfect that droidsound-e can play those files and not get stuck, but it works already in explorer and this is good, thanks

**Comment by droidmjt** [comment]
![cyrillicstuff](https://user-images.githubusercontent.com/5917820/60754551-4d07d280-9feb-11e9-8374-624a9f5e6371.png)

**Comment by droidmjt** [comment]
what problems it gives?

**Comment by Andr20** [comment]
![IMG_20190706_114415](https://user-images.githubusercontent.com/16883718/60754585-715fb100-9fe3-11e9-819b-e2adbcb2e993.png)

**Comment by droidmjt** [comment]
would it be possible to email me that song? easier to fix

**Comment by Andr20** [comment]
ok no problem

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/t92gsl1aaj4a1og/droidsounde167_174.apk?dl=1
try this

**Comment by Andr20** [comment]
The title is ok, now the artist gives the problem, if you change the name of the artist using the tag with cyrillic, however good job really, i am really happy for the support. it is a perfect app!!! REALLY!!!

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/g5791xepmp7ey86/droidsounde167_175.apk?dl=1
try this, should be fixed

**Comment by droidmjt** [comment]
leave a msg

**Comment by Andr20** [comment]
i just cheked it works great! THANK YOU! your app is the best player for music!
